components:
  schemas:
    ProductApiResponse:
      type: object
      properties:
        products:
          type: array
          items:
            $ref: "./ProductApi.yaml#/components/schemas/ProductApi"
