components:
  schemas:
    ProductApi:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        description:
          type: string
        price:
          type: integer
          format: int64