openapi: 3.0.3
info:
  title: Ecommerce openApi
  description: Ecommerce openApi
  version: 1.0.0
paths:
  /api/products:
    $ref: "./products/Products.yaml#/paths/~1api~1products"
  /api/products/{id}:
    $ref: "./products/Products.yaml#/paths/~1api~1products~1{id}"
  /api/orders:
    $ref: "./orders/Orders.yaml#/paths/~1api~1orders"
  /api/orders/{id}:
    $ref: "./orders/Orders.yaml#/paths/~1api~1orders~1{id}"
  /api/order-items:
    $ref: "./order-item/OrderItems.yaml#/paths/~1api~1order-items"
  /api/order-items/{id}:
    $ref: "./order-item/OrderItems.yaml#/paths/~1api~1order-items~1{id}"
