openapi: 3.0.3
info:
  title: Ecommerce openApi
  description: Ecommerce openApi
  version: 1.0.0
paths:
  /api/products:
    $ref: "./products/Products.yaml"
  /api/orders:
    $ref: "./orders/Orders.yaml"
